# Generated by Django 2.1.3 on 2018-11-14 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Ingredientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('preparacion', models.CharField(max_length=2000)),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuarios.Usuarios')),
                ('ingrediente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primer_ingrediente', to='Ingredientes.Ingrediente')),
                ('ingrediente2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segundo_ingrediente', to='Ingredientes.Ingrediente')),
                ('ingrediente3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tercer_ingrediente', to='Ingredientes.Ingrediente')),
                ('ingrediente4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuarto_ingrediente', to='Ingredientes.Ingrediente')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='receta/')),
                ('Receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recetas.Receta')),
            ],
        ),
    ]
